minor: [BLUEP-570] script for crawling events in azure
Kaleidoscope-Inc/aws-crawling pull request #3
Opened 2023-06-06 22:25 UTC by usmanklodhi

https://k6scope.atlassian.net/browse/BLUEP-570

2023-06-07 06:31 UTC, MDanialSaleem commented
The resource for event crawl and data crawl should be set up as part of a single terrform module.

2023-06-07 15:02 UTC, waleedakramkhan requested changes
minor comments

2023-06-07 15:02 UTC, waleedakramkhan commented on azure/kscope_crawl/main.tf
> +  name                  = "k6scopemycontainer"
```suggestion
  name                  = "kaleidoscopeactivitylogscontainer"
```

2023-06-07 15:02 UTC, waleedakramkhan commented on azure/kscope_crawl/main.tf
> +  name                 = "kscopemyqueue"
```suggestion
  name                 = "kaleidoscopeactivitylogsqueue"
```

2023-06-07 15:02 UTC, waleedakramkhan commented on azure/kscope_crawl/main.tf
> +resource "azurerm_monitor_diagnostic_setting" "storage_account_logs" {
can we do this for a subscription?

2023-06-19 20:49 UTC, usmanklodhi commented on azure/kscope_crawl/main.tf
> +  container_access_type = "private"
Applications outside the storage account's context will not have access to the container. By default, only the storage account owner and authorised users have access to the container.

2023-06-19 21:01 UTC, usmanklodhi commented on azure/kscope_crawl/main.tf
> +resource "azurerm_monitor_diagnostic_setting" "storage_account_logs" {
Diagnostic settings are not available at subscription level. I've checked thoroughly.

2023-06-19 21:33 UTC, usmanklodhi commented on azure/kscope_crawl/main.tf
> +  location = "eastus"
Name and location for resource group are now being sent as inputs.

2023-06-20 18:46 UTC, waleedakramkhan commented on azure/kscope_crawl/main.tf
> +  container_access_type = "private"
yes i get that but is our app also authorised to access this storage account and its blobs?

2023-06-20 20:48 UTC, usmanklodhi commented on azure/kscope_crawl/main.tf
> +  container_access_type = "private"
I think no, should i set the `container_access_type` to public?

2023-06-21 07:13 UTC, waleedakramkhan commented on azure/kscope_crawl/main.tf
> +  container_access_type = "private"
i think so, yes. otherwise we will get a access denied

2023-06-22 22:21 UTC, usmanklodhi commented on azure/kscope_crawl/main.tf
> +  container_access_type = "private"
The `container_access_type` is now container. It allows public access to the container and all the blobs within it. This means that anyone with the container URL can list and access all the blobs stored within the container.

2023-06-26 08:10 UTC, waleedakramkhan approved these changes
🚀

2023-06-26 08:42 UTC, merged